import { Inter } from "next/font/google";
import "./globals.css";
import Sliderbar from "./components/SliderBar";
import SlideBarToogle from "./components/SlideBarToogle";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Reportes BioTimePro",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.classNameName} bg-gray-50 dark:bg-slate-900`}>
        <SlideBarToogle />
        <Sliderbar />
        <div className="w-full pt-10 px-4 sm:px-6 md:px-8 lg:pl-72">
        
        { children }
        </div>
      </body>
    </html>
  );
}
