version: "3.8"

services:
  nextjs-app:
    container_name: nextjs-dev-container
    build:
      context: .
      dockerfile: Dockerfile
    image: probable-octo-memory:dev  # Define el nombre y la etiqueta de la imagen
    ports:
      - "40001:4000"
    volumes:
      - .:/app
      - /app/node_modules
      - /home/sistemas/docker/probable-octo-memory/public/resources_pdf:/app/public/resources_pdf
    environment:
      - NODE_ENV=development
    command: npx next dev -p 4000
    restart: unless-stopped
